// client/components/PlayerCard.vue
<script setup lang="ts">
import type { Player } from '@/types'
import { CLASSES, GENDERS, RACES } from '@/constants'
import { getLabel } from '@/lib/labels'
import { Card, CardContent } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'

defineProps<{
  player: Player
}>()
</script>

<template>
  <Card
    class="overflow-hidden transition-all hover:shadow-md border-2"
    :class="{ 'opacity-60': !player.connected }"
  >
    <!-- Top bar: name + power -->
    <div class="flex items-center justify-between px-4 py-3 bg-secondary/40">
      <div class="min-w-0 mr-2">
        <h3 class="font-bold text-base truncate text-foreground">
          {{ player.name }}
        </h3>
        <p v-if="!player.connected" class="text-xs text-muted-foreground">
          не в сети
        </p>
      </div>
      <div class="flex items-center gap-1.5 bg-primary text-primary-foreground rounded-xl px-3 py-1.5 shrink-0">
        <span class="text-xl font-extrabold leading-none tabular-nums">{{ player.level + player.gearBonus }}</span>
        <span class="text-[10px] font-medium opacity-80">СИЛА</span>
      </div>
    </div>

    <CardContent class="px-4 py-3 space-y-2.5">
      <!-- Stats row -->
      <div class="flex gap-3">
        <div class="flex-1 bg-secondary/30 rounded-lg px-3 py-2 text-center">
          <p class="text-[10px] text-muted-foreground font-medium uppercase tracking-wider">Уровень</p>
          <p class="text-lg font-bold text-foreground tabular-nums mt-0.5">{{ player.level }}</p>
        </div>
        <div class="flex-1 bg-secondary/30 rounded-lg px-3 py-2 text-center">
          <p class="text-[10px] text-muted-foreground font-medium uppercase tracking-wider">Бонусы</p>
          <p class="text-lg font-bold text-foreground tabular-nums mt-0.5">{{ player.gearBonus }}</p>
        </div>
      </div>

      <!-- Traits -->
      <div class="flex flex-wrap gap-1.5">
        <Badge variant="outline" class="flex-1 text-xs px-2 py-0.5">{{ getLabel(GENDERS, player.gender) }}</Badge>
        <Badge variant="outline" class="flex-1 text-xs px-2 py-0.5">{{ getLabel(RACES, player.race) }}</Badge>
        <Badge variant="outline" class="flex-1 text-xs px-2 py-0.5">{{ getLabel(CLASSES, player.class) }}</Badge>
      </div>
    </CardContent>
  </Card>
</template>

// apps/web/src/components/PlayerCard.tsx
import { CLASSES, GENDERS, getLabel, power, RACES, type Player } from '@munchkin/core'
import { Badge } from '@/components/ui/badge'
import { Card, CardContent } from '@/components/ui/card'

interface PlayerCardProps {
  player: Player
  isHost?: boolean
}

export function PlayerCard({ player, isHost = false }: PlayerCardProps) {
  return (
    <Card className={`gap-0 overflow-hidden border-2 py-0 transition-all hover:shadow-md ${player.connected ? '' : 'opacity-60'}`}>
      <div className="flex items-center justify-between bg-secondary/40 px-4 py-3">
        <div className="mr-2 min-w-0">
          <h3 className="truncate text-base font-bold text-foreground">
            {player.name}
            {isHost && <span className="text-xs font-normal text-muted-foreground"> · хост</span>}
          </h3>
          {!player.connected && <p className="text-xs text-muted-foreground">не в сети</p>}
        </div>
        <div className="flex shrink-0 items-center gap-1.5 rounded-xl bg-primary px-3 py-1.5 text-primary-foreground">
          <span className="text-xl leading-none font-extrabold tabular-nums">{power(player)}</span>
          <span className="text-[10px] font-medium opacity-80">СИЛА</span>
        </div>
      </div>

      <CardContent className="space-y-2.5 px-4 py-3">
        <div className="flex gap-3">
          <Stat label="Уровень" value={player.level} />
          <Stat label="Бонусы" value={player.gearBonus} />
        </div>
        <div className="flex flex-wrap gap-1.5">
          {[getLabel(GENDERS, player.gender), getLabel(RACES, player.race), getLabel(CLASSES, player.class)].map((t, i) => (
            <Badge key={i} variant="outline" className="flex-1 px-2 py-0.5 text-xs">
              {t}
            </Badge>
          ))}
        </div>
      </CardContent>
    </Card>
  )
}

function Stat({ label, value }: { label: string; value: number }) {
  return (
    <div className="flex-1 rounded-lg bg-secondary/30 px-3 py-2 text-center">
      <p className="text-[10px] font-medium tracking-wider text-muted-foreground uppercase">{label}</p>
      <p className="mt-0.5 text-lg font-bold text-foreground tabular-nums">{value}</p>
    </div>
  )
}
