// apps/web/src/pages/RoomPage.tsx
import {
  MAX_LEVEL,
  selectAllPlayers,
  selectConnected,
  selectCurrentPlayer,
  selectHasOlder,
  selectHost,
  selectIsFinished,
  selectIsHost,
  selectOtherPlayers,
} from '@munchkin/core'
import { Flag, Swords } from 'lucide-react'
import { useEffect, useRef, useState } from 'react'
import { useNavigate, useParams } from 'react-router'
import { ChangeLog } from '@/components/ChangeLog'
import { CombatMode } from '@/components/CombatMode'
import { FinishGameDialog } from '@/components/FinishGameDialog'
import { GameSummary } from '@/components/GameSummary'
import { PlayerCard } from '@/components/PlayerCard'
import { RoomHeader } from '@/components/RoomHeader'
import { StatsEditor } from '@/components/StatsEditor'
import { Button } from '@/components/ui/button'
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog'
import { gameActions, gameStore, useGame, useGameShallow } from '@/game/store'

export default function RoomPage() {
  const { code = '' } = useParams()
  const navigate = useNavigate()

  const roomCode = useGame((s) => s.roomCode)
  const playerId = useGame((s) => s.playerId)
  const connected = useGame(selectConnected)
  const me = useGame(selectCurrentPlayer)
  const others = useGameShallow(selectOtherPlayers)
  const players = useGameShallow(selectAllPlayers)
  const isHost = useGame(selectIsHost)
  const host = useGame(selectHost)
  const isFinished = useGame(selectIsFinished)
  const changelog = useGame((s) => s.changelog)
  const hasOlder = useGame(selectHasOlder)
  const loadingOlder = useGame((s) => s.loadingOlder)
  const { winnerId, createdAt, finishedAt } = useGameShallow((s) => ({
    winnerId: s.winnerId,
    createdAt: s.createdAt,
    finishedAt: s.finishedAt,
  }))

  const [finishOpen, setFinishOpen] = useState(false)
  const [suggestedWinner, setSuggestedWinner] = useState<string>()

  // Opened directly (reload, shared link): resume our seat or go home
  const [resuming, setResuming] = useState(() => !gameStore.getState().roomCode)
  useEffect(() => {
    if (gameStore.getState().roomCode) return
    void gameActions()
      .resumeSession(code)
      .then((result) => {
        if (result !== 'resumed') navigate(`/?code=${encodeURIComponent(code)}`, { replace: true })
      })
      .finally(() => setResuming(false))
  }, [code, navigate])

  // The room was closed under us (not found, replaced by another tab)
  useEffect(() => {
    if (!roomCode && !resuming && gameStore.getState().notice) navigate('/', { replace: true })
  }, [roomCode, resuming, navigate])

  // Someone just reached the last level: offer the host to finish with them as winner
  const previousLevels = useRef(new Map<string, number>())
  useEffect(() => {
    const before = previousLevels.current
    if (isHost && !isFinished) {
      const champion = players.find((p) => {
        const was = before.get(p.id)
        return was !== undefined && was < MAX_LEVEL && p.level === MAX_LEVEL
      })
      if (champion) {
        setSuggestedWinner(champion.id)
        setFinishOpen(true)
      }
    }
    previousLevels.current = new Map(players.map((p) => [p.id, p.level]))
  }, [players, isHost, isFinished])

  function leave() {
    gameActions().leaveRoom()
    navigate('/', { replace: true })
  }

  function openFinish() {
    setSuggestedWinner(undefined)
    setFinishOpen(true)
  }

  async function copyCode() {
    try {
      await navigator.clipboard.writeText(roomCode || code)
    } catch {
      // the code is visible anyway
    }
  }

  const journal = (
    <ChangeLog entries={changelog} hasOlder={hasOlder} loadingOlder={loadingOlder} onLoadOlder={() => gameActions().loadOlder()} />
  )

  return (
    <div className="flex min-h-dvh flex-col bg-background">
      {roomCode && <RoomHeader code={roomCode} connected={connected} onLeave={leave} />}

      <main className="mx-auto w-full max-w-4xl flex-1 space-y-5 px-3 py-4 pb-[max(1rem,env(safe-area-inset-bottom))] sm:space-y-6 sm:px-4 sm:py-6">
        {resuming || !me ? (
          <Waiting text={resuming ? 'Переподключение...' : 'Подключение...'} />
        ) : isFinished ? (
          <>
            <GameSummary
              players={players}
              playerId={playerId}
              winnerId={winnerId}
              createdAt={createdAt}
              finishedAt={finishedAt}
              onLeave={leave}
            />
            {journal}
          </>
        ) : (
          <>
            <StatsEditor player={me} isHost={isHost} onChange={(stats) => gameActions().updateStats(stats)} />
            {journal}

            <Dialog>
              <DialogTrigger asChild>
                <Button variant="outline" className="h-10 w-full">
                  <Swords aria-hidden="true" />
                  Режим боя
                </Button>
              </DialogTrigger>
              <DialogContent>
                <DialogHeader>
                  <DialogTitle>⚔️ Режим боя</DialogTitle>
                </DialogHeader>
                <CombatMode players={players} />
              </DialogContent>
            </Dialog>

            {isHost ? (
              <Button variant="ghost" className="h-10 w-full text-muted-foreground" disabled={!connected} onClick={openFinish}>
                <Flag aria-hidden="true" />
                Завершить игру
              </Button>
            ) : (
              host && (
                <p className="text-center text-xs text-muted-foreground">Завершить игру может хост — {host.name}</p>
              )
            )}

            {others.length > 0 ? (
              <section>
                <div className="mb-3 flex items-center gap-2 sm:mb-4">
                  <h2 className="text-base font-bold text-foreground sm:text-lg">Другие игроки</h2>
                  <span className="rounded-full bg-secondary px-2 py-0.5 text-xs text-muted-foreground">{others.length}</span>
                </div>
                <div className="grid grid-cols-1 gap-3 sm:grid-cols-2 sm:gap-4 lg:grid-cols-3">
                  {others.map((p) => (
                    <PlayerCard key={p.id} player={p} isHost={p.id === host?.id} />
                  ))}
                </div>
              </section>
            ) : (
              connected && (
                <div className="flex flex-col items-center justify-center py-12 text-center sm:py-16">
                  <div className="mb-4 animate-bounce text-4xl select-none" aria-hidden="true">
                    ⏳
                  </div>
                  <p className="text-base font-medium text-muted-foreground">Ожидание других игроков...</p>
                  <p className="mt-1 text-sm text-muted-foreground/70">Поделитесь кодом комнаты</p>
                  <button
                    type="button"
                    onClick={copyCode}
                    className="mt-3 rounded-lg bg-secondary px-4 py-2 font-mono text-sm font-bold tracking-wider transition-colors hover:bg-accent active:scale-95"
                  >
                    {roomCode}
                  </button>
                </div>
              )
            )}

            {isHost && (
              <FinishGameDialog
                open={finishOpen}
                onOpenChange={setFinishOpen}
                players={players}
                playerId={playerId}
                suggestedWinnerId={suggestedWinner}
                onFinish={(winner) => gameActions().finishGame(winner)}
              />
            )}
          </>
        )}
      </main>
    </div>
  )
}

function Waiting({ text }: { text: string }) {
  return (
    <div className="flex flex-col items-center justify-center py-12 text-center sm:py-16">
      <div className="mb-4 size-8 animate-spin rounded-full border-3 border-primary border-t-transparent" aria-hidden="true" />
      <p className="text-base font-medium text-muted-foreground">{text}</p>
    </div>
  )
}

// client/pages/RoomPage.vue
<script setup lang="ts">
import { ref, watch } from 'vue'
import { Flag, Swords } from 'lucide-vue-next'
import { useRouter, useRoute } from 'vue-router'
import { useClipboard } from '@vueuse/core'
import { useRoomStore } from '@/stores/room'
import { loadSession, clearSession } from '@/services/sessionStorage'
import { getRoomInfo } from '@/services/roomApi'
import RoomHeader from '@/components/RoomHeader.vue'
import StatsEditor from '@/components/StatsEditor.vue'
import PlayerCard from '@/components/PlayerCard.vue'
import ChangeLog from '@/components/ChangeLog.vue'
import CombatMode from '@/components/CombatMode.vue'
import FinishGameDialog from '@/components/FinishGameDialog.vue'
import GameSummary from '@/components/GameSummary.vue'
import { MAX_LEVEL } from '@/constants'
import {
  Dialog,
  DialogTrigger,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogClose,
} from '@/components/ui/dialog'
import { Button } from '@/components/ui/button'

const router = useRouter()
const route = useRoute()
const roomStore = useRoomStore()
const { copy } = useClipboard()

const rejoining = ref(false)
const combatOpen = ref(false)
const finishOpen = ref(false)
const suggestedWinnerId = ref('')

if (!roomStore.roomCode) {
  // Not in a room from normal flow — try session restore
  const session = loadSession()
  const routeCode = (route.params.code as string)?.toUpperCase()

  if (session && session.roomCode === routeCode) {
    rejoining.value = true
    tryRejoin(session.roomCode, session.playerName, session.sessionId)
  } else {
    // Opened via a shared link: ask for a name with the code prefilled
    router.replace({ name: 'home', query: routeCode ? { code: routeCode } : {} })
  }
}

// Watch for roomCode clearing (e.g. server error "room not found")
watch(() => roomStore.roomCode, (code) => {
  if (!code && !rejoining.value) {
    router.replace({ name: 'home' })
  }
})

// Reaching the last level: offer to finish the game with yourself as winner
watch(() => roomStore.currentPlayer?.level, (level, previous) => {
  if (previous !== undefined && level === MAX_LEVEL && previous < MAX_LEVEL && !roomStore.isFinished) {
    openFinishDialog(roomStore.playerId)
  }
})

function openFinishDialog(winnerId = '') {
  suggestedWinnerId.value = winnerId
  finishOpen.value = true
}

function leaveFinishedGame() {
  roomStore.leaveRoom()
  router.push({ name: 'home' })
}

async function tryRejoin(code: string, name: string, sessionId: string) {
  try {
    await getRoomInfo(code)
    roomStore.rejoinRoom(code, name, sessionId)
  } catch {
    clearSession()
    roomStore.notice = 'Комната не найдена или уже закрыта'
    router.replace({ name: 'home' })
  } finally {
    rejoining.value = false
  }
}

function copyRoomCode() {
  copy(roomStore.roomCode)
}
</script>

<template>
  <div class="min-h-dvh bg-background flex flex-col">
    <RoomHeader v-if="roomStore.roomCode" />

    <main class="flex-1 w-full max-w-4xl mx-auto px-3 sm:px-4 py-4 sm:py-6 space-y-5 sm:space-y-6 safe-area-bottom">
      <!-- Rejoining state -->
      <div
        v-if="rejoining"
        class="flex flex-col items-center justify-center py-12 sm:py-16 text-center"
      >
        <div class="w-8 h-8 border-3 border-primary border-t-transparent rounded-full animate-spin mb-4" />
        <p class="text-base font-medium text-muted-foreground">
          Переподключение...
        </p>
      </div>

      <template v-else-if="roomStore.roomCode && roomStore.isFinished">
        <GameSummary @leave="leaveFinishedGame" />
        <ChangeLog />
      </template>

      <template v-else-if="roomStore.roomCode">
        <!-- Stats Editor for current player -->
        <StatsEditor />

        <!-- Change Log -->
        <ChangeLog />

        <!-- Combat Mode Dialog -->
        <Dialog v-model:open="combatOpen">
          <DialogTrigger as-child>
            <Button variant="outline" class="w-full">
              <Swords class="size-4" />
              Режим боя
            </Button>
          </DialogTrigger>
          <DialogContent>
            <DialogClose />
            <DialogHeader>
              <DialogTitle>⚔️ Режим боя</DialogTitle>
            </DialogHeader>
            <CombatMode :open="combatOpen" />
          </DialogContent>
        </Dialog>

        <Button
          variant="ghost"
          class="w-full text-muted-foreground"
          :disabled="!roomStore.connected"
          @click="openFinishDialog()"
        >
          <Flag class="size-4" />
          Завершить игру
        </Button>
        <FinishGameDialog v-model:open="finishOpen" :suggested-winner-id="suggestedWinnerId" />

        <!-- Other players -->
        <section v-if="roomStore.otherPlayers.length > 0">
          <div class="flex items-center gap-2 mb-3 sm:mb-4">
            <h2 class="text-base sm:text-lg font-bold text-foreground">Другие игроки</h2>
            <span class="text-xs text-muted-foreground bg-secondary rounded-full px-2 py-0.5">
              {{ roomStore.otherPlayers.length }}
            </span>
          </div>
          <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3 sm:gap-4">
            <PlayerCard
              v-for="player in roomStore.otherPlayers"
              :key="player.id"
              :player="player"
            />
          </div>
        </section>

        <!-- Waiting state -->
        <div
          v-else-if="roomStore.connected && roomStore.allPlayers.length <= 1"
          class="flex flex-col items-center justify-center py-12 sm:py-16 text-center"
        >
          <div class="text-4xl mb-4 animate-bounce select-none" aria-hidden="true">
            ⏳
          </div>
          <p class="text-base font-medium text-muted-foreground">
            Ожидание других игроков...
          </p>
          <p class="text-sm text-muted-foreground/70 mt-1">
            Поделитесь кодом комнаты
          </p>
          <button
            class="mt-3 text-sm font-mono font-bold bg-secondary hover:bg-accent px-4 py-2 rounded-lg transition-colors active:scale-95 cursor-pointer tracking-wider"
            @click="copyRoomCode"
          >
            {{ roomStore.roomCode }}
          </button>
        </div>

        <!-- Connecting state -->
        <div
          v-else-if="!roomStore.connected"
          class="flex flex-col items-center justify-center py-12 sm:py-16 text-center"
        >
          <div class="w-8 h-8 border-3 border-primary border-t-transparent rounded-full animate-spin mb-4" />
          <p class="text-base font-medium text-muted-foreground">
            Подключение...
          </p>
        </div>
      </template>
    </main>
  </div>
</template>

<style scoped>
.safe-area-bottom {
  padding-bottom: max(1rem, env(safe-area-inset-bottom));
}
</style>
