// apps/web/src/components/StatsEditor.tsx
import {
  CLASSES,
  clampGearBonus,
  clampLevel,
  GENDERS,
  MAX_GEAR_BONUS,
  MAX_LEVEL,
  MIN_GEAR_BONUS,
  MIN_LEVEL,
  power,
  RACES,
  type Option,
  type Player,
  type PlayerStats,
} from '@munchkin/core'
import { Button } from '@/components/ui/button'
import { Card, CardContent } from '@/components/ui/card'
import { Label } from '@/components/ui/label'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { Separator } from '@/components/ui/separator'

interface StatsEditorProps {
  player: Player
  isHost: boolean
  onChange: (stats: Partial<PlayerStats>) => void
}

export function StatsEditor({ player, isHost, onChange }: StatsEditorProps) {
  return (
    <Card className="gap-0 overflow-hidden border-2 border-primary/50 py-0 shadow-md">
      <div className="bg-primary/5 px-4 py-4 sm:px-6 sm:py-5">
        <div className="flex items-center justify-between">
          <div className="min-w-0">
            <p className="text-sm font-medium text-muted-foreground">
              Ваш персонаж{isHost && ' · хост'}
            </p>
            <h2 className="truncate text-lg font-bold text-foreground sm:text-xl">{player.name}</h2>
          </div>
          <div className="ml-3 flex shrink-0 flex-col items-center rounded-2xl bg-primary px-4 py-2 text-primary-foreground shadow-sm sm:px-5 sm:py-3">
            <span className="text-3xl leading-none font-extrabold sm:text-4xl" aria-label={`Сила ${power(player)}`}>
              {power(player)}
            </span>
            <span className="mt-0.5 text-[10px] font-medium opacity-80 sm:text-xs" aria-hidden="true">
              СИЛА
            </span>
          </div>
        </div>
      </div>

      <CardContent className="space-y-5 px-4 py-4 sm:px-6 sm:py-5">
        <div className="grid grid-cols-2 gap-3 sm:gap-4">
          <Stepper
            label="Уровень"
            value={player.level}
            canDecrease={player.level > MIN_LEVEL}
            canIncrease={player.level < MAX_LEVEL}
            onStep={(d) => onChange({ level: clampLevel(player.level + d) })}
          />
          <Stepper
            label="Бонусы"
            value={player.gearBonus}
            canDecrease={player.gearBonus > MIN_GEAR_BONUS}
            canIncrease={player.gearBonus < MAX_GEAR_BONUS}
            onStep={(d) => onChange({ gearBonus: clampGearBonus(player.gearBonus + d) })}
          />
        </div>

        <Separator />

        <div className="flex flex-wrap gap-1.5">
          <TraitSelect label="Пол" value={player.gender} options={GENDERS} onChange={(gender) => onChange({ gender })} />
          <TraitSelect label="Раса" value={player.race} options={RACES} onChange={(race) => onChange({ race })} />
          <TraitSelect label="Класс" value={player.class} options={CLASSES} onChange={(cls) => onChange({ class: cls })} />
        </div>
      </CardContent>
    </Card>
  )
}

interface StepperProps {
  label: string
  value: number
  canDecrease: boolean
  canIncrease: boolean
  onStep: (delta: 1 | -1) => void
}

function Stepper({ label, value, canDecrease, canIncrease, onStep }: StepperProps) {
  const buttonClass =
    'size-10 shrink-0 rounded-xl text-lg font-bold transition-transform active:scale-90 sm:size-11'
  return (
    <div className="rounded-xl bg-secondary/50 p-3 sm:p-4" role="group" aria-label={label}>
      <span className="text-xs font-medium text-muted-foreground sm:text-sm">{label}</span>
      <div className="mt-2 flex items-center justify-between">
        <Button variant="outline" className={buttonClass} disabled={!canDecrease} onClick={() => onStep(-1)} aria-label={`${label}: меньше`}>
          −
        </Button>
        <span className="text-2xl font-extrabold text-foreground tabular-nums sm:text-3xl" aria-live="polite">
          {value}
        </span>
        <Button variant="outline" className={buttonClass} disabled={!canIncrease} onClick={() => onStep(1)} aria-label={`${label}: больше`}>
          +
        </Button>
      </div>
    </div>
  )
}

interface TraitSelectProps<T extends string> {
  label: string
  value: T
  options: Option<T>[]
  onChange: (value: T) => void
}

function TraitSelect<T extends string>({ label, value, options, onChange }: TraitSelectProps<T>) {
  const id = `trait-${label}`
  return (
    <div className="space-y-1.5">
      <Label htmlFor={id} className="text-xs font-medium text-muted-foreground sm:text-sm">
        {label}
      </Label>
      <Select value={value} onValueChange={(v) => onChange(v as T)}>
        <SelectTrigger id={id} className="data-[size=default]:h-11">
          <SelectValue />
        </SelectTrigger>
        <SelectContent>
          {options.map((o) => (
            <SelectItem key={o.value} value={o.value}>
              {o.label}
            </SelectItem>
          ))}
        </SelectContent>
      </Select>
    </div>
  )
}

// client/components/StatsEditor.vue
<script setup lang="ts">
import { usePlayerStats } from '@/composables/usePlayerStats'
import { CLASSES, GENDERS, MAX_GEAR_BONUS, MAX_LEVEL, MIN_GEAR_BONUS, MIN_LEVEL, RACES } from '@/constants'
import type { PlayerStats } from '@/types'
import { Card, CardContent } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Label } from '@/components/ui/label'
import { Separator } from '@/components/ui/separator'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'

const { player, power, changeLevel, changeGear, updateAttribute } = usePlayerStats()

function onSelectUpdate<K extends keyof PlayerStats>(key: K, value: unknown) {
  if (typeof value === 'string') updateAttribute(key, value as PlayerStats[K])
}
</script>

<template>
  <Card v-if="player" class="border-2 border-primary/50 shadow-md overflow-hidden">
    <!-- Power hero section -->
    <div class="bg-primary/5 px-4 sm:px-6 py-4 sm:py-5">
      <div class="flex items-center justify-between">
        <div class="min-w-0">
          <p class="text-sm text-muted-foreground font-medium">Ваш персонаж</p>
          <h2 class="text-lg sm:text-xl font-bold text-foreground truncate">{{ player.name }}</h2>
        </div>
        <div class="flex flex-col items-center bg-primary text-primary-foreground rounded-2xl px-4 sm:px-5 py-2 sm:py-3 shadow-sm shrink-0 ml-3">
          <span class="text-3xl sm:text-4xl font-extrabold leading-none">{{ power }}</span>
          <span class="text-[10px] sm:text-xs font-medium opacity-80 mt-0.5">СИЛА</span>
        </div>
      </div>
    </div>

    <CardContent class="px-4 sm:px-6 py-4 sm:py-5 space-y-5">
      <!-- Level & Gear in a row on mobile -->
      <div class="grid grid-cols-2 gap-3 sm:gap-4">
        <!-- Level -->
        <div class="bg-secondary/50 rounded-xl p-3 sm:p-4">
          <Label class="text-xs sm:text-sm font-medium text-muted-foreground">Уровень</Label>
          <div class="flex items-center justify-between mt-2">
            <Button
              variant="outline"
              size="icon"
              class="h-10 w-10 sm:h-11 sm:w-11 rounded-xl text-lg font-bold shrink-0 active:scale-90 transition-transform"
              :disabled="player.level <= MIN_LEVEL"
              @click="changeLevel(-1)"
            >
              −
            </Button>
            <span class="text-2xl sm:text-3xl font-extrabold text-foreground tabular-nums">
              {{ player.level }}
            </span>
            <Button
              variant="outline"
              size="icon"
              class="h-10 w-10 sm:h-11 sm:w-11 rounded-xl text-lg font-bold shrink-0 active:scale-90 transition-transform"
              :disabled="player.level >= MAX_LEVEL"
              @click="changeLevel(1)"
            >
              +
            </Button>
          </div>
        </div>

        <!-- Gear Bonus -->
        <div class="bg-secondary/50 rounded-xl p-3 sm:p-4">
          <Label class="text-xs sm:text-sm font-medium text-muted-foreground">Бонусы</Label>
          <div class="flex items-center justify-between mt-2">
            <Button
              variant="outline"
              size="icon"
              class="h-10 w-10 sm:h-11 sm:w-11 rounded-xl text-lg font-bold shrink-0 active:scale-90 transition-transform"
              :disabled="player.gearBonus <= MIN_GEAR_BONUS"
              @click="changeGear(-1)"
            >
              −
            </Button>
            <span class="text-2xl sm:text-3xl font-extrabold text-foreground tabular-nums">
              {{ player.gearBonus }}
            </span>
            <Button
              variant="outline"
              size="icon"
              class="h-10 w-10 sm:h-11 sm:w-11 rounded-xl text-lg font-bold shrink-0 active:scale-90 transition-transform"
              :disabled="player.gearBonus >= MAX_GEAR_BONUS"
              @click="changeGear(1)"
            >
              +
            </Button>
          </div>
        </div>
      </div>

      <Separator />

      <!-- Selects: stack on mobile, grid on desktop -->
      <div class="flex flex-wrap gap-1.5">
        <!-- Gender -->
        <div class="space-y-1.5">
          <Label class="text-xs sm:text-sm font-medium text-muted-foreground">Пол</Label>
          <Select :model-value="player.gender" @update:model-value="(v) => onSelectUpdate('gender', v)">
            <SelectTrigger class="h-11">
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              <SelectItem v-for="g in GENDERS" :key="g.value" :value="g.value">
                {{ g.label }}
              </SelectItem>
            </SelectContent>
          </Select>
        </div>

        <!-- Race -->
        <div class="space-y-1.5">
          <Label class="text-xs sm:text-sm font-medium text-muted-foreground">Раса</Label>
          <Select :model-value="player.race" @update:model-value="(v) => onSelectUpdate('race', v)">
            <SelectTrigger class="h-11">
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              <SelectItem v-for="r in RACES" :key="r.value" :value="r.value">
                {{ r.label }}
              </SelectItem>
            </SelectContent>
          </Select>
        </div>

        <!-- Class -->
        <div class="space-y-1.5">
          <Label class="text-xs sm:text-sm font-medium text-muted-foreground">Класс</Label>
          <Select :model-value="player.class" @update:model-value="(v) => onSelectUpdate('class', v)">
            <SelectTrigger class="h-11">
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              <SelectItem v-for="c in CLASSES" :key="c.value" :value="c.value">
                {{ c.label }}
              </SelectItem>
            </SelectContent>
          </Select>
        </div>
      </div>
    </CardContent>
  </Card>
</template>
